import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pépouze la crêperie du 12",
  description: "Generated by create next app",
  openGraph: {
    title: "Pépouze la crêperie du 12",
    description:
      "A creative web studio crafting immersive, premium and accessible digital experiences.",
    url: "https://pepouze-la-creperie-du-12.vercel.app",
    siteName: "Pépouze la crêperie du 12",
    images: [
      {
        url: "https://pepouze-la-creperie-du-12.vercel.app/og-image.png",
        width: 1200,
        height: 630,
        alt: "Pépouze la crêperie du 12",
      },
    ],
    locale: "fr_FR",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
